// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rivttlezosjsivoozbfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpdnR0bGV6b3Nqc2l2b296YmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNTIyNzIsImV4cCI6MjA2NzgyODI3Mn0.HlHiGbbOElSysl0v3g5nG9TIv49wlC0gjmdhh2YwIuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});